public class CaseHandler {
    /*public static void onBeforeInsert(List<Case> newCases) {
        for (Case caseVar : newCases) {
            if (caseVar.Origin == 'email') {
                caseVar.Status = 'working';
                caseVar.Priority = 'low';
            }
        }
    }

    public static void onBeforeUpdate(List<Case> updatedCases, Map<Id, Case> oldMapCases) {
        for (Case caseVar : updatedCases) {
            Case oldCase = oldMapCases.get(caseVar.Id);
            if (caseVar.Origin == 'email' && caseVar.Origin != oldCase.Origin) {
                caseVar.Status = 'working';
                caseVar.Priority = 'low';
            }
        }
    }*/
}